### ISSUE TITLE
Logovanie projektu

### ISSUE THREAD

**Issue by smehylova** [FRI-UNIZA/jumpeno#21]

**Comment by Andydas** [comment]
Je potrebne : 
- [ ] aktualny loger nahradit novym -> log4net
- [ ] vytvorit service na odosielanie vynimiek
- [ ] obalit trycatchom **await builder.Build().RunAsync();** v program.cs a vyskusat
- [ ] pridat na clientovi moznost stiahnut logy zo servera (v adminpaneli)

**Comment by Andydas** [comment]
Obalit trycatchom await builder.Build().RunAsync() nepojde, je potrebne 
- [ ] pouzit ErrorBoundary na odchytavanie vynimiek.
